#!/usr/bin/env bash
#
# Generate the native_sim end-to-end PARITY tree from the existing snapshot
# suite (§5.2 of docs/architecture-redesign.md).
#
# For every existing case under tests/{core,feedback,events}/<case> that has a
# native_sim.keymap + keycode_events.snapshot, emit a parity case under
# tests/parity/e2e/<suite>__<case>/ that:
#   - drives the SAME keymap (by relative #include of the original), and
#   - builds the NEW deep-module stack (CONFIG_..._NEW_STACK=y appended to the
#     original conf), and
#   - asserts the SAME snapshot (the legacy path's recorded output is the oracle).
#
# If the new stack reproduces every legacy snapshot, that IS old-vs-new
# end-to-end parity — the step-8 cut-over gate. The urob keymap-snapshot runner
# discovers these by native_sim.keymap and diffs keycode_events.snapshot, exactly
# as it does the legacy cases.
#
# Re-run after adding/changing a legacy case; the generated tree is committed so
# CI runs it without needing this script.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/../../.." && pwd)"
out="$here"

cfg="CONFIG_ZMK_BEHAVIOR_DYNAMIC_MACRO_NEW_STACK=y"

# Cases excluded from the parity tree (space-separated "suite/case").
#
# core/pool_full is new-stack-only: it exercises the shared-arena "pool full"
# rejection, which has no legacy equivalent (the legacy per-slot arrays would
# simply store all three macros). It already sets NEW_STACK=y in its own conf,
# so there is no legacy oracle to mirror — generating a twin would just duplicate
# the same new-stack run against the same snapshot.
EXCLUDE="core/pool_full"

generated=0
for suite in core feedback events; do
  for case_dir in "$repo/tests/$suite"/*/; do
    case="$(basename "$case_dir")"
    [ -f "$case_dir/native_sim.keymap" ] || continue
    [ -f "$case_dir/keycode_events.snapshot" ] || continue
    case " $EXCLUDE " in *" $suite/$case "*) continue ;; esac

    dst="$out/${suite}__${case}"
    mkdir -p "$dst"

    # keymap: drive the identical events by including the legacy keymap. Its own
    # "../behavior_keymap.dtsi" include resolves relative to the legacy file, so
    # the shared keymap is reused unchanged.
    {
      echo "/* GENERATED by tests/parity/e2e/generate.sh — do not edit. */"
      echo "/* Parity: same input as tests/$suite/$case, new stack, same snapshot. */"
      echo "#include \"../../../$suite/$case/native_sim.keymap\""
    } > "$dst/native_sim.keymap"

    # conf: legacy conf + the new-stack switch.
    {
      cat "$case_dir/native_sim.conf"
      echo "$cfg"
    } > "$dst/native_sim.conf"

    # snapshot + patterns: copied verbatim (the legacy output is the oracle).
    cp "$case_dir/keycode_events.snapshot" "$dst/keycode_events.snapshot"
    [ -f "$case_dir/events.patterns" ] && cp "$case_dir/events.patterns" "$dst/events.patterns"

    generated=$((generated + 1))
  done
done

echo "Generated $generated parity cases under $out"
